export const initialRecords = [
  { id: 1, studentName: "Alan", score: 100, studentClass: "A" },
  { id: 2, studentName: "Jessica", score: 50, studentClass: "A" },
  { id: 3, studentName: "Sarah", score: 70, studentClass: "B" },
  { id: 4, studentName: "Ade", score: 80, studentClass: "B" },
  { id: 5, studentName: "Tariq", score: 60, studentClass: "C" },
  { id: 6, studentName: "Shaun", score: 100, studentClass: "C" },
  { id: 7, studentName: "Michaela", score: 10, studentClass: "C" },
  { id: 8, studentName: "Robin", score: 20, studentClass: "B" },
  { id: 9, studentName: "John", score: 30, studentClass: "A" },
];
/*
  { id: 10, studentName: "Peter", score: 95, studentClass: "A" },
  { id: 11, studentName: "Oscar", score: 85, studentClass: "A" },
  { id: 12, studentName: "Jenny", score: 55, studentClass: "A" },
  { id: 13, studentName: "Malik", score: 70, studentClass: "B" },
  { id: 14, studentName: "Muhammed", score: 85, studentClass: "B" },
  { id: 15, studentName: "Paul", score: 55, studentClass: "C" },
  { id: 16, studentName: "Ian", score: 45, studentClass: "C" },
  { id: 17, studentName: "Jane", score: 15, studentClass: "C" },
  { id: 18, studentName: "George", score: 25, studentClass: "B" },
  { id: 19, studentName: "Adnan", score: 75, studentClass: "A" },
  { id: 20, studentName: "Lewis", score: 5, studentClass: "A" },
  { id: 21, studentName: "Ellijah", score: 35, studentClass: "A" },
  { id: 22, studentName: "Jimin", score: 55, studentClass: "B" },
  { id: 23, studentName: "Alexander", score: 65, studentClass: "B" },
  { id: 24, studentName: "Mindy", score: 80, studentClass: "C" },
  { id: 25, studentName: "Issa", score: 100, studentClass: "C" },
  { id: 26, studentName: "Molly", score: 10, studentClass: "C" },
  { id: 27, studentName: "Olivia", score: 20, studentClass: "B" },
  { id: 28, studentName: "Ak", score: 100, studentClass: "A" },
];
*/
